import { IData } from './utils/types';

export const CategoriesGenres = [
  {
    id: 0,
    img: 'https://img.freepik.com/free-photo/rpa-concept-with-blurry-hand-touching-screen_23-2149311914.jpg',
    genre: 'ComputerScience',
  },
  {
    id: 1,
    img: 'https://img.freepik.com/free-photo/top-view-books-plants-arrangement_23-2148785101.jpg',
    genre: 'NaturalSciences',
  },
  {
    id: 2,
    img: 'https://img.freepik.com/free-photo/mini-globe-top-textbook-pile_23-2148199824.jpg',
    genre: 'SocialSciences',
  },
  {
    id: 3,
    img: 'https://img.freepik.com/free-photo/bible-wood-cross-candles_1150-17676.jpg',
    genre: 'Religion&Theology',
  },
];

export const productList: IData[] = [
  {
    id: 1,
    gtin: '978-0241316757',
    category: 'Books',
    type: 'Politics',
    title: 'The Origins Of Totalitarianism',
    image: 'https://m.media-amazon.com/images/I/81JZJ0elZ1L._SL1500_.jpg',
    creator: 'Hannah Arendt',
    description:
      'The Origins of Totalitarianism begins with the rise of anti-Semitism in central and western Europe in the 1800s and continues with an examination of European colonial imperialism from 1884 to the outbreak of World War I. Arendt explores the institutions and operations of totalitarian movements, focusing on the two genuine forms of totalitarian government in our time—Nazi Germany and Stalinist Russia—which she adroitly recognizes were two sides of the same coin, rather than opposing philosophies of Right and Left. From this vantage point, she discusses the evolution of classes into masses, the role of propaganda in dealing with the nontotalitarian world, the use of terror, and the nature of isolation and loneliness as preconditions for total domination.',
    release_date: '2017-01-01',
    language: 'English',
    publisher: 'Penguin Modern Classics',
    stock: 20,
    ratings: 4.6,
    listprice: 485,
    discount: 0,
    popularItem: false,
    comments: 701,
  },
  {
    id: 2,
    gtin: '978-0545162074',
    category: 'Books',
    type: 'Fiction',
    title: 'Harry Potter Paperback Box Set (Books 1-7)',
    image: 'https://m.media-amazon.com/images/I/51v0gkGIaKL._SL1200_.jpg',
    creator: 'J. K. Rowling',
    description:
      'Now for the first time ever, J.K. Rowling’s seven bestselling Harry Potter books are available in a stunning paperback boxed set! The Harry Potter series has been hailed as “one for the ages” by Stephen King and “a spellbinding saga’ by USA Today. And most recently, The New York Times called Harry Potter and the Deathly Hallows the “fastest selling book in history.” This is the ultimate Harry Potter collection for Harry Potter fans of all ages!',
    release_date: '2009-07-01',
    language: 'English',
    publisher: 'Scholastic Inc.',
    stock: 37,
    ratings: 4.9,
    listprice: 3710,
    discount: 20,
    popularItem: false,
    comments: 11034,
  },
  {
    id: 3,
    gtin: '978-1119796763',
    category: 'Books',
    type: 'ComputerScience',
    title: 'Artificial Intelligence For Dummies',
    image: 'https://m.media-amazon.com/images/I/81KieAp28yL._SL1500_.jpg',
    creator: 'John Paul Mueller',
    description:
      'Every time you use a smart device or some sort of slick technology―be it a smartwatch, smart speaker, security alarm, or even customer service chat box―you’re engaging with artificial intelligence (AI). If you’re curious about how AI is developed―or question whether AI is real―Artificial Intelligence For Dummies holds the answers you’re looking for. Starting with a basic definition of AI and explanations of data use, algorithms, special hardware, and more, this reference simplifies this complex topic for anyone who wants to understand what operates the devices we can’t live without.',
    release_date: '2021-11-24',
    language: 'English',
    publisher: 'For Dummies',
    stock: 40,
    ratings: 4.1,
    listprice: 950,
    discount: 5,
    popularItem: true,
    comments: 45,
  },
  {
    id: 4,
    gtin: '883929704736',
    category: 'Videos',
    type: 'Blu-ray',
    title:
      'The Lord of the Rings: The Motion Picture Trilogy (Extended & Theatrical)(4K Ultra HD + Digital)',
    image: 'https://m.media-amazon.com/images/I/71h7HHb9lIL._SL1500_.jpg',
    creator: undefined,
    description:
      'This critically acclaimed epic trilogy follows the quest undertaken by the hobbit, Frodo Baggins, and his fellowship of companions to save Middle-earth by destroying the One Ring and defeating the evil forces of the Dark Lord Sauron.',
    release_date: '2021-11-24',
    language: 'English',
    publisher: 'Warner Bros',
    stock: 31,
    ratings: 4.8,
    listprice: 3800,
    discount: 20,
    popularItem: false,
    comments: 37000,
  },
  {
    id: 5,
    gtin: 'LGT46573BR',
    category: 'Videos',
    type: 'Blu-ray',
    title: 'John Wick',
    image: 'https://m.media-amazon.com/images/I/71TPtV8DDVL._SL1393_.jpg',
    creator: undefined,
    description:
      'When sadistic young thugs senselessly attack John Wick - a brilliantly lethal ex-assassin - they have no idea that they′ve just awakened the boogeyman. With New York City as his bullet-riddled playground, Wick embarks on a merciless rampage, hunting down his adversaries with the skill and ruthlessness that made him an underworld legend.',
    release_date: '2017-02-07',
    language: 'English Subtitles:English, Spanish',
    publisher: 'Lionsgate Home Entertainment',
    stock: 40,
    ratings: 4.8,
    listprice: 660,
    discount: 0,
    popularItem: false,
    comments: 105381,
  },
  {
    id: 6,
    gtin: 'B06XXCTXX1',
    category: 'Videos',
    type: 'Blu-ray',
    title: 'John Wick: Chapter 2 - 4K Ultra Hd [Blu-ray] [4K UHD]',
    image: 'https://m.media-amazon.com/images/I/71UmgeXe96L._SL1500_.jpg',
    creator: undefined,
    description:
      'John Wick is forced out of retirement, and this time, he must face off against a shadowy international assassins′ guild and more of the world′s deadliest killers.',
    release_date: '2017-06-13',
    language: 'English Subtitles:English, Spanish',
    publisher: 'Lionsgate Home Entertainment',
    stock: 3,
    ratings: 4.8,
    listprice: 660,
    discount: 0,
    popularItem: false,
    comments: 17316,
  },
];

export const searchList = [{}, {}, {}];

export const popItems = [
  {
    id: 3,
    gtin: '978-1119796763',
    title: 'Artificial Intelligence For Dummies',
    listprice: 950,
    ratings: 4.1,
    comments: 45,
    image: 'https://m.media-amazon.com/images/I/81KieAp28yL._SL1500_.jpg',
  },
  {
    id: 8,
    gtin: 'B0BZ5C5XNJ',
    category: 'Videos',
    type: 'Blu-ray',
    title: 'John Wick: Chapter 4 [Blu-ray]',
    image: 'https://m.media-amazon.com/images/I/81J1DaRKzUL._SL1500_.jpg',
    creator: null,
    ratings: 4.6,
    listprice: 665,
    popularItem: 1,
    comments: 40319,
  },
  {
    id: 9,
    gtin: '4710756122456',
    category: 'Videos',
    type: 'Blu-ray',
    title: 'Dungeons & Dragons: Honor Among Thieves (BD)',
    image: 'https://m.media-amazon.com/images/I/813oHCxIbfL._SL1500_.jpg',
    ratings: 4.4,
    listprice: 960,
    discout: 0,
    popularItem: 1,
    comments: 18973,
  },
  {
    id: 10,
    gtin: '9789861755267',
    category: 'Books',
    type: 'Psychology',
    title: '原子習慣',
    image: 'https://s.eslite.com/upload/product/o/2681759319001/ec1760858.jpg',
    creator: '詹姆斯．克利爾',
    ratings: 4.1,
    listprice: 330,
    discout: 20,
    popularItem: 1,
    comments: 50731,
  },
];

export const politicsRelated = [
  {
    id: 0,
    img: 'https://m.media-amazon.com/images/I/51ml1jD4sfL._AC_UY327_FMwebp_QL65_.jpg',
    name: 'Bringing the State Back In',
    genre: 'Politics',
  },
  {
    id: 1,
    img: 'https://s2.eslite.com/unsafe/fit-in/x900/s.eslite.com/Upload/Product/200910/o/633924946848049582.jpg',
    name: '極權主義的起源',
    genre: 'Politics',
  },
  {
    id: 2,
    img: 'https://upload.wikimedia.org/wikipedia/zh/b/b9/Clash_civilizations.jpg',
    name: 'The Clash Of Civilizations',
    genre: 'Politics',
  },
];

export const MovieRelated = [
  {
    id: 0,
    img: 'https://i.ebayimg.com/images/g/-F8AAOSwW4NlT0k2/s-l1600.jpg',
    name: 'The Continental: From the World of John Wick (2023) Blu-ray BD 2 Disc',
  },
  {
    id: 1,
    img: 'https://m.media-amazon.com/images/I/71nnbGLSqZL._SL1255_.jpg',
    name: 'Mission:Impossible - Dead Reckoning Part One [Blu-ray]',
  },
];
